pull_requests:
  do_not_increment_build_number: true
version: '{build}'
branches:
  only:
  - master
shallow_clone: true
image: Visual Studio 2017
build_script:
  - mkdir build
  - cd build
  - cmake ../byond-extools
  - cmake --build . --config RelWithDebInfo
artifacts:
  - path: build/RelWithDebInfo/byond-extools.dll
  - path: build/RelWithDebInfo/byond-extools.pdb
