name: Build

on: 
 push: 
   branches: master
 pull_request: 
   branches: master

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.0
      with:
        github-api-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Linux
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo dpkg --add-architecture i386
        sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
        sudo apt-get install g++-10-multilib llvm-10-dev
        mkdir build
        mkdir yogs
        cd build
        cmake ../byond-extools -DCMAKE_BUILD_TYPE=RelWithDebInfo
        cmake --build .
        cd ../yogs
        cmake ../byond-extools -DCMAKE_BUILD_TYPE=Yogs
        cmake --build .
      env:
        CC:   clang
        CXX:  clang++

    - name: Prepare Artifacts
      run: |
        mkdir artifacts
        mkdir yogs-artifacts
        cp build/libbyond-extools.so artifacts
        cp yogs/libbyond-extools.so yogs-artifacts

    - name: Upload General Artifacts
      uses: actions/upload-artifact@v1
      with: 
        name: Linux
        path: ${{github.workspace}}/artifacts

    - name: Upload Yogs Artifacts
      uses: actions/upload-artifact@v1
      with: 
        name: Yogs
        path: ${{github.workspace}}/yogs-artifacts

  windows:
     runs-on: windows-2019
     steps:
     - uses: actions/checkout@v2
     
     - name: Build Windows
       run: |
         mkdir build
         cd build
         cmake ../byond-extools -A Win32 
         cmake --build . --config RelWithDebInfo
         
     - name: Prepare Artifacts
       run: |
        mkdir artifacts
        cp build/RelWithDebInfo/byond-extools.dll artifacts
        cp build/RelWithDebInfo/byond-extools.pdb artifacts

     - name: Upload Artifacts
       uses: actions/upload-artifact@v1
       with: 
         name: Windows
         path: ${{github.workspace}}/artifacts
